# Generated by Django 2.1.2 on 2018-11-27 02:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import photo_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='geolocation',
            field=models.TextField(blank=True, max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to=photo_blog.models.get_image_path),
        ),
    ]
